# fly.toml file generated for codeday-calendar-gql on 2023-05-24T10:08:56-07:00

app = "codeday-calendar-gql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

[experimental]
  auto_rollback = true
