# fly.toml file generated for codeday-calendar-gql on 2021-11-17T10:22:26-05:00

app = "codeday-calendar-gql"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
